### ISSUE TITLE
Can we get a v9 version please - varbase is expecting it.

### ISSUE THREAD

**Issue by HeneryH** [Vardot/varbase_seo#2]
Problem 1
    - drupal/varbase_blog 9.0.x-dev requires drupal/varbase_seo ^9 || 9.0.x-dev -> no matching package found.
    - vardot/varbase 9.0.x-dev requires drupal/varbase_blog 9.0.x-dev -> satisfiable by drupal/varbase_blog[9.0.x-dev].
    - Installation request for vardot/varbase 9.0.x-dev -> satisfiable by vardot/varbase[9.0.x-dev].

**Comment by Natshah** [comment]
Thanks, Henery for reporting.
Varbase 9.0.0-rc1 was released
Closing this issue
